### ISSUE TITLE
[BUG] chameleon-tabs should only show secondary colour when selected

### ISSUE THREAD

**Issue by ryuhhnn** [MaritzSTL/chameleon#110]
**Describe the bug**
Tab should be #c4c7ca when not selected and show secondary colour when selected
<img width="979" alt="Screenshot 2019-10-11 at 11 38 45" src="https://user-images.githubusercontent.com/10367396/66668821-b6673500-ec1b-11e9-88f5-8e5e70e875d0.png">

**Comment by dschandrasekara** [comment]
@ryuhhnn i would like to work on this

**Comment by ryuhhnn** [comment]
Thanks for the interest in contributing to Chameleon @dschandrasekara, it looks like another contributor is already on it, but if you're looking for another easy one, you can check out #83
