### ISSUE TITLE
[FEATURE REQUEST] New Element: chameleon-filterable-search

### ISSUE THREAD

**Issue by kewalter** [MaritzSTL/chameleon#129]
A search field component which can filter out a list of items.

**Comment by kewalter** [comment]
This may be duplicate work of https://github.com/MaritzSTL/chameleon/issues/21

**Comment by kewalter** [comment]
![image](https://user-images.githubusercontent.com/1884893/68137726-12586d00-feed-11e9-8faf-1f12ebb1661a.png)
In our current non-chameleon components, the "group name" search field is just a text input.  
The Type (filter by) field is a "filterable search" component, which sounds like how you described the multiselect.  I'm confused on the difference.

**Comment by ryuhhnn** [comment]
Going to go ahead and close this since I think we all are in agreement that the `chameleon-multiselect` will serve the purpose of this. Feel free to reopen this should that change
