### ISSUE TITLE
[BUG] chameleon-input text has hover style

### ISSUE THREAD

**Issue by ryuhhnn** [MaritzSTL/chameleon#148]
**Describe the bug**
When hovering over the chameleon-input, if it has text in it, you can trigger the secondary hover styles by mousing over. 

**Expected behavior**
This is unexpected and the text inside the input should not change on hover

**Screenshots**
<img width="239" alt="Screenshot 2019-10-28 at 19 58 05" src="https://user-images.githubusercontent.com/10367396/67729027-819a0280-f9bd-11e9-94aa-6fcb9e777712.png">

**Comment by kewalter** [comment]
closed by https://github.com/MaritzSTL/chameleon/pull/163
