### ISSUE TITLE
round edges in circular chameleon-loader

### ISSUE THREAD

**Issue by ryuhhnn** [MaritzSTL/chameleon#155]
Let's round the edges of the line in the spinner to be more consistent with our design language

<img width="36" alt="Screenshot 2019-10-29 at 10 47 53" src="https://user-images.githubusercontent.com/10367396/67784412-be0b4400-fa39-11e9-8f33-58e0f688926a.png">

**Comment by kewalter** [comment]
I don't think there's an easy way to round the ends with the current way the spinner is rendered.  It's using a border to render the rings and hiding the overflow of the div to cut off the ends, so it's just a straight line with no way to round it.  We'd need to move to some kind of svg or something for it.
