### ISSUE TITLE
[FEATURE REQUEST] RFC: Namespaced CustomEvents

### ISSUE THREAD

**Issue by ryuhhnn** [MaritzSTL/chameleon#188]
Right now, there are some inconsistent CustomEvents that are being thrown. We might want to just prefix all CustomEvents with `chameleon.` for consistency and clarity sake

**Comment by ZempTime** [comment]
Couple choices here.

The higher-level dimensions are:
* `<eventname>`
* `chameleon-<eventname>`
* `chameleon-<tagname>-<eventname>`

Delimiters could be `-` or `.`. (Personally I think `.` is prettier).

And we could potentially employ abbreviation. Assuming `.` delimiter -

Examples:
1. `colorchange`
2. `chameleon.colorchange`
3. `chameleon.riceballdessert.colorchange`
4. `cha.colorchange`
5. `cha.riceballdessert.colorchange`

**Comment by kewalter** [comment]
I agree, I prefer `.` as a delimiter.  I think adding the tag name/component name is a good ideas to help prevent collisions and to be more clear.  Any downsides to doing that?

**Comment by kewalter** [comment]
For reference, here's the list of custom events I currently see in the components:
```chip
  remove-chip

dialog
  toggle-dialog

multiselect
  chameleon.select

paginator
  page-change

select
  chameleon.select
  chameleon-select.close

sheet
  toggle-sheet

tab
  selected-changed

toast
  close-toast```

**Comment by ryuhhnn** [comment]
I'm torn between:
`chameleon.COMPONENT-ACTION`
and
`chameleon.COMPONENT.ACTION`

Either seem fine to me! We can always put it to a vote :)

**Comment by ZempTime** [comment]
Some observations:

* we're already putting the component name in (sheet's `toggle-sheet`)
* we're using both `.` and `-` as delimiters in different places. Insofar as that's concerned, I have a slight preference to adhere to the way browsers name events: all lowercase, all one word, and imperative. (So not `toggled`, but `toggle`)

Looks like there are possibly categories of events we could standardize across components, even if they had different `<tagname>` sections -
* all events related to form input
* all events related to "thing happened." Should we be able to cancel events, actually? (preventDefault would prevent a sheet toggle?)

**Comment by nodza** [comment]
Since this was still up for debate, here's my vote - following @kewalter's approach with the input component. But I am definitely fine with changing it if people prefer something else.

**Comment by ryuhhnn** [comment]
Closing with the solution: `<component_name>.<event_name>`
