### ISSUE TITLE
[FEATURE REQUEST] Add Default Gradient to chameleon-card-image

### ISSUE THREAD

**Issue by ryuhhnn** [MaritzSTL/chameleon#191]
<img width="331" alt="Screenshot 2019-11-11 at 14 56 39" src="https://user-images.githubusercontent.com/10367396/68620610-7a7df480-0493-11ea-8ba8-8bae77a620fa.png">

Default to gradient when no image URL is given

**Comment by CJ-4** [comment]
I would like to work on this issue.

**Comment by ryuhhnn** [comment]
@CJ-4 awesome, it's yours!!! Feel free to reach out at any time if you have questions 😄

**Comment by ryuhhnn** [comment]
Here is the value you'll need: `linear-gradient(to top, var(--color-primary-dark, #004587), var(--color-primary-light, #679dea));`
