### ISSUE TITLE
New Element: chameleon-toggle

### ISSUE THREAD

**Issue by ryuhhnn** [MaritzSTL/chameleon#232]
<img width="863" alt="Screenshot 2019-11-21 at 15 09 50" src="https://user-images.githubusercontent.com/10367396/69377055-14525800-0c71-11ea-948b-bc951f5023e0.png">

**Comment by kewalter** [comment]
Is this a toggle like a true/false boolean?  How would this look if we were wanting a toggle that was just for turning a setting on/off?

**Comment by ryuhhnn** [comment]
@kewalter not necessarily, I think chameleon-switch serves that purpose better. The toggle element can have 2+ different toggles and functions kind of like the tabs component in a way. Each toggle should accept an icon and a title to display

**Comment by ryuhhnn** [comment]
Closing this since UX has made the decision to make this the design for the tabs
