### ISSUE TITLE
[BUG] chameleon-multiselect should close when clicked outside of

### ISSUE THREAD

**Issue by ryuhhnn** [MaritzSTL/chameleon#240]
**Expected behavior**
When the multiselect is opened, clicking anywhere outside of it should close it

**Comment by tfreiner** [comment]
https://github.com/MaritzSTL/chameleon/pull/234 should have taken care of this issue

**Comment by ryuhhnn** [comment]
Oops sorry for that oversight! Thank you for being on top of this @tfreiner !
