### ISSUE TITLE
Disabled attribute for input component not applied to underlying control

### ISSUE THREAD

**Issue by jetters** [MaritzSTL/chameleon#304]
**Describe the bug**
The disabled attribute for the Chameleon input control is not disabling the input control. The style in the wrapper div is updated appropriately, but the control is still enabled. It appears the disabled attribute is not being applied to the underlying input control.

**Expected behavior**
When applying the disabled attribute to the Chameleon input component, the user should not be able to click into or use/modify the input control.

**Comment by ryuhhnn** [comment]
Closed with #307
