### ISSUE TITLE
Unit Testing Strategy

### ISSUE THREAD

**Issue by ryuhhnn** [MaritzSTL/chameleon#32]
We will need to determine our testing strategy:

* possibly use karma for unit testing
* make sure that tests are being run in the pre-push husky hook
* could our testing strategy help us determine what a minor vs. major version bump is?
* snapshot testing
* possibly implementing open-wc standards for testing

I probably missed a lot of stuff here so feel free to add to this list. cc: @ZempTime @terrencebowen

**Comment by ZempTime** [comment]
I agree we should go in on [Open WC's](https://open-wc.org/testing/) testing approach.

We should also document and communicate what browser's we're targeting support for, and hook up CI to run said tests across all of said browsers.

Finally, this is outside the scope of unit testing, but we should also consider the use of screenshot regression testing as this is a heavily visual project.
