### ISSUE TITLE
Icon spills outside of input field when an error exists

### ISSUE THREAD

**Issue by ryuhhnn** [MaritzSTL/chameleon#37]
Whenever there is an error on an input field that has an icon, the icon will be pushed to the end of the container

![screen_shot_2019-08-27_at_3 57 29_pm](https://user-images.githubusercontent.com/10367396/63898347-4039a680-c9be-11e9-9f55-c68aff58d222.png)

**Comment by dewstend** [comment]
How can I replicate this bug?

**Comment by ryuhhnn** [comment]
@dewstend you can recreate this in Storybook using the `npm run dev` command (or: https://maritzstl.github.io/chameleon/?path=/story/input--icon-right) by going to the Input -> "Icon Right" story and filling in a very long error message (see screenshot above)

**Comment by Emizel** [comment]
Can I take this?

**Comment by ryuhhnn** [comment]
@Emizel go for it! I'll go ahead and assign you

**Comment by ryuhhnn** [comment]
@Emizel this is stale so I'm going to go ahead and reassign this to myself and take care of it

**Comment by ryuhhnn** [comment]
@Emizel the README.md file has been updated with new instructions. This project is now using `yarn` as a dependency manager, and we've removed the need to use a Makefile. You're welcome to pick this back up if you can get your environment working, and feel free to reach out if you're still having issues!
