### ISSUE TITLE
New Element: chameleon-table

### ISSUE THREAD

**Issue by ryuhhnn** [MaritzSTL/chameleon#59]

**Comment by kewalter** [comment]
Is there any use case for just a table component that is different from a basic implementation of "filterable-table" component?  Should we just call filterable-table, table?

**Comment by ryuhhnn** [comment]
@kewalter my original thinking in this was that there might be use for a chameleon styled table component, however, I do see how making it be its own webcomponent might be overkill. I'm cool with closing this and maybe reopening it if we find a use case for it in the future!

**Comment by kewalter** [comment]
@ryuhhnn Think we should just rename filterable-table to simply `table` or leave it as `filterable-table` for now just in case?

**Comment by ryuhhnn** [comment]
@kewalter I haven't looked too deep into this yet,  but if you made it where we can "toggle" on and off the filtering options, go ahead and go with `table` but if the filtering is baked into the component, I'd say leave it as `filterable-table` for now

**Comment by kewalter** [comment]
The filtering, searching, and sorting are completely optional.  I'm going to just call the component `table`.
