### ISSUE TITLE
[FEATURE REQUEST] Add `href` option to chameleon-button

### ISSUE THREAD

**Issue by ryuhhnn** [MaritzSTL/chameleon#95]
**Is your feature request related to a problem? Please describe.**

Currently, if a button is used to link to another page, you have to add a `@click` handler to handle that request.

**Describe the solution you'd like**
It would be nice to just have a `href` attribute that you can use on the button that will do this for you. Syntax for doing this would be a lot more succinct and readable.

**Comment by kewalter** [comment]
Resolved by https://github.com/MaritzSTL/chameleon/pull/138
